
version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - users-db:/var/lib/postgresql/data

  app:
    build:
      context: .
    links:
      - postgres:postgres
    environment:
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  users-db:
